resources:
  containers:
  - container: ubuntu
    image:  wpilib/ubuntu-base:18.04

stages:
- stage: Check
  jobs:
  - job: Check
    pool:
      vmImage: 'Ubuntu 16.04'

    container: ubuntu

    steps:
        - script: |
            sudo pip3 install pyelftools pefile
          displayName: 'Install dependencies'
        - script: |
            ./check.py 2019/*.json
          displayName: 'Run check'
